title: 0 から始める Jekyll 超入門  # サイトのタイトル
description: >- # サイトの説明を書く
  サイトの説明を書いてください。
  200文字程度がいいと一般には言われていたりします。


baseurl: "" # ここは無視してOKです
url: "https://<type-your-domain>" # サイトのドメインを入力します。

plugins: # 使用するプラグインがあればここに追加します
  - jekyll-feed

exclude: # サイトの生成に含めないものをここに追加します
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
